<a href="https://colab.research.google.com/github/SwethaVipparla/Tensorflow/blob/master/RNN/RNN_Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.2.0


In [2]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

In [4]:
# Make some data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [5]:
# Make an RNN
M = 5 # number of hidden units
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [6]:
# Get the output
Yhat = model.predict(X)
print(Yhat)

[[-0.84964097 -0.12828799]]


In [7]:
# See if we can replicate this output
# Get the weights first
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 5)                 45        
_________________________________________________________________
dense (Dense)                (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [8]:
# See what's returned
model.layers[1].get_weights()

[array([[ 0.00740629, -0.80443305,  0.11332941, -0.25444806, -0.47888023],
        [ 0.8393845 ,  0.43830568,  0.5362008 ,  0.39856   , -0.2249403 ],
        [-0.31344587, -0.03854156,  0.7319191 ,  0.0576629 , -0.56313133]],
       dtype=float32),
 array([[-5.7339764e-01, -3.9955050e-01, -6.2671460e-02,  7.1248674e-01,
          3.0799587e-03],
        [ 1.7881013e-01, -7.2601527e-01,  3.8273895e-01, -2.3168857e-01,
          4.9067295e-01],
        [ 1.2606890e-04,  1.3291585e-01, -6.7306745e-01,  1.2289668e-02,
          7.2743565e-01],
        [-4.0058792e-01,  5.2030736e-01,  5.9852326e-01,  2.0058198e-02,
          4.5845082e-01],
        [ 6.9193304e-01,  1.5771703e-01,  1.9578882e-01,  6.6191375e-01,
          1.4103517e-01]], dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [9]:
# Check their shapes
# Should make sense
# First output is input > hidden
# Second output is hidden > hidden
# Third output is bias term (vector of length M)
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [10]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [11]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo # we only care about this value on the last iteration
  Yhats.append(y)
  
  # important: assign h to h_last
  h_last = h

# print the final output
print(Yhats[-1])

[-0.849641   -0.12828807]
